import = [ "~/.config/alacritty/catppuccin.toml"]

[shell]
program = "zellij"

[font]
normal = { family = "CaskaydiaMono NF", style = "Regular" }
bold = { family = "CaskaydiaMono NF", style = "Bold" }
italic = { family = "CaskaydiaMono NF", style = "Italic" }
size = 10

[window]
dimensions.columns = 90
dimensions.lines = 60
# padding.x = 15
# padding.y = 15
opacity = 0.97
decorations = "Full"
decorations_theme_variant = "Dark"

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" },
  { key = "N", mods= "Control|Shift", action = "CreateNewWindow" }
]
