#!/bin/sh
#
# Usage:
#
#    sh install.sh
#
# Environment variables: VERBOSE, CP, LN, MKDIR, RM, DIRNAME.
#
#    env VERBOSE=1 sh install.sh
#
# DO NOT EDIT THIS FILE
# 
# This file is generated by rcm(7) as:
#
#   rcup -x README.md -x install.sh -g
#
# To update it, re-run the above command.
#
: ${VERBOSE:=0}
: ${CP:=/bin/cp}
: ${LN:=/bin/ln}
: ${MKDIR:=/bin/mkdir}
: ${RM:=/bin/rm}
: ${DIRNAME:=/usr/bin/dirname}
verbose() {
  if [ "$VERBOSE" -gt 0 ]; then
    echo "$@"
  fi
}
handle_file_cp() {
  if [ -e "$2" ]; then
    printf "%s " "overwrite $2? [yN]"
    read overwrite
    case "$overwrite" in
      y)
        $RM -rf "$2"
        ;;
      *)
        echo "skipping $2"
        return
        ;;
    esac
  fi
  verbose "'$1' -> '$2'"
  $MKDIR -p "$($DIRNAME "$2")"
  $CP -R "$1" "$2"
}
handle_file_ln() {
  if [ -e "$2" ]; then
    printf "%s " "overwrite $2? [yN]"
    read overwrite
    case "$overwrite" in
      y)
        $RM -rf "$2"
        ;;
      *)
        echo "skipping $2"
        return
        ;;
    esac
  fi
  verbose "'$1' -> '$2'"
  $MKDIR -p "$($DIRNAME "$2")"
  $LN -sf "$1" "$2"
}
handle_file_ln "/home/sergej/.dotfiles/atom/config.cson" "/home/sergej/.atom/config.cson"
handle_file_ln "/home/sergej/.dotfiles/atom/init.coffee" "/home/sergej/.atom/init.coffee"
handle_file_ln "/home/sergej/.dotfiles/atom/keymap.cson" "/home/sergej/.atom/keymap.cson"
handle_file_ln "/home/sergej/.dotfiles/atom/packages.cson" "/home/sergej/.atom/packages.cson"
handle_file_ln "/home/sergej/.dotfiles/atom/snippets.cson" "/home/sergej/.atom/snippets.cson"
handle_file_ln "/home/sergej/.dotfiles/gitconfig" "/home/sergej/.gitconfig"
handle_file_ln "/home/sergej/.dotfiles/vim/after/syntax/xml.vim" "/home/sergej/.vim/after/syntax/xml.vim"
handle_file_ln "/home/sergej/.dotfiles/vim/autoload/plug.vim" "/home/sergej/.vim/autoload/plug.vim"
handle_file_ln "/home/sergej/.dotfiles/vim/colors/wombat.vim" "/home/sergej/.vim/colors/wombat.vim"
handle_file_ln "/home/sergej/.dotfiles/vim/indent/html.vim" "/home/sergej/.vim/indent/html.vim"
handle_file_ln "/home/sergej/.dotfiles/vimrc" "/home/sergej/.vimrc"
handle_file_ln "/home/sergej/.dotfiles/zimrc" "/home/sergej/.zimrc"
handle_file_ln "/home/sergej/.dotfiles/zlogin" "/home/sergej/.zlogin"
handle_file_ln "/home/sergej/.dotfiles/zprofile" "/home/sergej/.zprofile"
handle_file_ln "/home/sergej/.dotfiles/zshrc" "/home/sergej/.zshrc"
