#!/bin/sh
#
# Usage:
#
#    sh install.sh
#
# Environment variables: VERBOSE, CP, LN, MKDIR, RM, DIRNAME.
#
#    env VERBOSE=1 sh install.sh
#
# DO NOT EDIT THIS FILE
# 
# This file is generated by rcm(7) as:
#
#   rcup -g
#
# To update it, re-run the above command.
#
: ${VERBOSE:=0}
: ${CP:=/bin/cp}
: ${LN:=/bin/ln}
: ${MKDIR:=/bin/mkdir}
: ${RM:=/bin/rm}
: ${DIRNAME:=/usr/bin/dirname}
verbose() {
  if [ "$VERBOSE" -gt 0 ]; then
    echo "$@"
  fi
}
handle_file_cp() {
  if [ -e "$2" ]; then
    printf "%s " "overwrite $2? [yN]"
    read overwrite
    case "$overwrite" in
      y)
        $RM -rf "$2"
        ;;
      *)
        echo "skipping $2"
        return
        ;;
    esac
  fi
  verbose "'$1' -> '$2'"
  $MKDIR -p "$($DIRNAME "$2")"
  $CP -R "$1" "$2"
}
handle_file_ln() {
  if [ -e "$2" ]; then
    printf "%s " "overwrite $2? [yN]"
    read overwrite
    case "$overwrite" in
      y)
        $RM -rf "$2"
        ;;
      *)
        echo "skipping $2"
        return
        ;;
    esac
  fi
  verbose "'$1' -> '$2'"
  $MKDIR -p "$($DIRNAME "$2")"
  $LN -sf "$1" "$2"
}
handle_file_ln "/home/sergej/.dotfiles/bash_profile" "/home/sergej/.bash_profile"
handle_file_ln "/home/sergej/.dotfiles/bashrc" "/home/sergej/.bashrc"
handle_file_ln "/home/sergej/.dotfiles/config/nvim/init.lua" "/home/sergej/.config/nvim/init.lua"
handle_file_ln "/home/sergej/.dotfiles/config/nvim/lazy-lock.json" "/home/sergej/.config/nvim/lazy-lock.json"
handle_file_ln "/home/sergej/.dotfiles/config/nvim/lazyvim.json" "/home/sergej/.config/nvim/lazyvim.json"
handle_file_ln "/home/sergej/.dotfiles/config/nvim/LICENSE" "/home/sergej/.config/nvim/LICENSE"
handle_file_ln "/home/sergej/.dotfiles/config/nvim/lua/config/autocmds.lua" "/home/sergej/.config/nvim/lua/config/autocmds.lua"
handle_file_ln "/home/sergej/.dotfiles/config/nvim/lua/config/keymaps.lua" "/home/sergej/.config/nvim/lua/config/keymaps.lua"
handle_file_ln "/home/sergej/.dotfiles/config/nvim/lua/config/lazy.lua" "/home/sergej/.config/nvim/lua/config/lazy.lua"
handle_file_ln "/home/sergej/.dotfiles/config/nvim/lua/config/options.lua" "/home/sergej/.config/nvim/lua/config/options.lua"
handle_file_ln "/home/sergej/.dotfiles/config/nvim/lua/plugins/example.lua" "/home/sergej/.config/nvim/lua/plugins/example.lua"
handle_file_ln "/home/sergej/.dotfiles/config/nvim/lua/plugins/theme.lua" "/home/sergej/.config/nvim/lua/plugins/theme.lua"
handle_file_ln "/home/sergej/.dotfiles/config/nvim/plugin/after/transparency.lua" "/home/sergej/.config/nvim/plugin/after/transparency.lua"
handle_file_ln "/home/sergej/.dotfiles/config/nvim/stylua.toml" "/home/sergej/.config/nvim/stylua.toml"
handle_file_ln "/home/sergej/.dotfiles/config/xkb/rules/evdev.xml" "/home/sergej/.config/xkb/rules/evdev.xml"
handle_file_ln "/home/sergej/.dotfiles/config/xkb/symbols/ru" "/home/sergej/.config/xkb/symbols/ru"
handle_file_ln "/home/sergej/.dotfiles/config/xkb/symbols/sk" "/home/sergej/.config/xkb/symbols/sk"
handle_file_ln "/home/sergej/.dotfiles/config/xkb/symbols/typo" "/home/sergej/.config/xkb/symbols/typo"
handle_file_ln "/home/sergej/.dotfiles/gitconfig" "/home/sergej/.gitconfig"
handle_file_ln "/home/sergej/.dotfiles/git-prompt.sh" "/home/sergej/.git-prompt.sh"
handle_file_ln "/home/sergej/.dotfiles/inputrc" "/home/sergej/.inputrc"
handle_file_ln "/home/sergej/.dotfiles/rcrc" "/home/sergej/.rcrc"
handle_file_ln "/home/sergej/.dotfiles/vim/after/syntax/xml.vim" "/home/sergej/.vim/after/syntax/xml.vim"
handle_file_ln "/home/sergej/.dotfiles/vim/autoload/plug.vim" "/home/sergej/.vim/autoload/plug.vim"
handle_file_ln "/home/sergej/.dotfiles/vim/colors/wombat.vim" "/home/sergej/.vim/colors/wombat.vim"
handle_file_ln "/home/sergej/.dotfiles/vim/indent/html.vim" "/home/sergej/.vim/indent/html.vim"
handle_file_ln "/home/sergej/.dotfiles/vimrc" "/home/sergej/.vimrc"
handle_file_ln "/home/sergej/.dotfiles/zimrc" "/home/sergej/.zimrc"
handle_file_ln "/home/sergej/.dotfiles/zshenv" "/home/sergej/.zshenv"
handle_file_ln "/home/sergej/.dotfiles/zshrc" "/home/sergej/.zshrc"
