#!/bin/sh
# [Gedit Tool]
# Comment=Spustiť „make“ v adresári dokumentu
# Name=Zostavenie
# Shortcut=<Control>F8
# Languages=
# Applicability=local
# Output=output-panel
# Input=nothing
# Save-files=nothing


EHOME=`echo $HOME | sed "s/#/\#/"`
DIR=$GEDIT_CURRENT_DOCUMENT_DIR
while test "$DIR" != "/"; do
    for m in GNUmakefile makefile Makefile; do
        if [ -f "${DIR}/${m}" ]; then
            echo "Using ${m} from ${DIR}" | sed "s#$EHOME#~#" > /dev/stderr
            make -C "${DIR}"
            exit
        fi
    done
    DIR=`dirname "${DIR}"`
done
~/.local/bin/build.sh $GEDIT_CURRENT_DOCUMENT_NAME
